export const ADMIN_ROUTE = '/admin'
export const HOME_ROUTE = '/'
export const WORKS_ROUTE = '/works/:state'
export const NEWS_ROUTE = '/news'
export const AUTH_ROUTE = '/auth'
export const LOGOUT_ROUTE = '/logout'
export const ARTICLE_ROUTE = '/article/:id'
export const BOOKS_ROUTE = '/books'